name: PR Workflow
on:
  pull_request: 
      branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  first:
    name: pretend the CI Clojure Setup workflow
    uses: ./.github/workflows/clojure-setup.yml
   
  second:
    name: pretend the firebase hosting PR workflow
    needs: first
    uses: ./.github/workflows/firebase-hosting-pull-request.yml