name: PR Workflow

on:
  pull_request: 
      branches:
      - main

jobs:
  first:
    name: pretend the CI Clojure Setip workflow
    uses: murilinhoPs/ace-of-cards/.github/workflows/firebase-hosting-pull-request.yml@@test-deploy
   
  second:
    name: pretend the firebase hosting PR workflow
    needs: first
    uses: murilinhoPs/ace-of-cards/.github/workflows/clojure-setup.yml@test-deploy
    